
PLAY [production] **************************************************************

TASK [Update Windows] **********************************************************
fatal: [172.19.1.22]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.1.22', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61ce5b0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.34]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.34', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61c0bb0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.37]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.37', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61c7970>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.1.24]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.1.24', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61cb790>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.1.25]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.1.25', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61cc880>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.39]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.39', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61c0f70>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.41]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.41', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6158a00>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.53]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.53', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61d1a90>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.61]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.61', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61cee50>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.67]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.67', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61cef70>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.69]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.69', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d616a730>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.73]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.73', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61694c0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.104]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.104', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d615cd90>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.97]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.97', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61629a0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.106]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.106', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6178370>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.107]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.107', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d617a5e0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.110]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.110', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6184340>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.108]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.108', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6165c70>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.115]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.115', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61855e0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.111]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.111', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6186040>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.116]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.116', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61699a0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.123]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.123', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6298760>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.120]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.120', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6186340>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.125]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.125', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d62539d0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.124]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.124', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6c2a880>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.126]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.126', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6253520>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.128]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.128', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d610e220>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.132]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.132', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d78ac940>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.129]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.129', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d63064f0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.130]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.130', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d78ac760>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.135]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.135', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d610c190>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.138]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.138', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6188490>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.140]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.140', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6185880>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.141]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.141', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6177040>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.143]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.143', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d617cdc0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.144]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.144', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d61181f0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.145]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.145', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6112400>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.148]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.148', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6113700>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.173]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.173', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6183070>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.157]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.157', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6182a90>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.174]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.174', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6129040>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.209]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.209', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6127640>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.210]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.210', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d611f730>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.212]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.212', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6110ca0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.216]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.216', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d610fcd0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.224]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.224', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6112f40>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.233]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.233', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d612d280>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.253]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.253', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d612b670>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.19.7.254]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.19.7.254', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d612a5e0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.20.8.19]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.20.8.27]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.20.8.41]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 753
fatal: [172.20.8.16]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Searching for updates: Exception from HRESULT: 0x80072F8F - Unknown WUA HRESULT 2147954575 (UNKNOWN 80072F8F)", "reboot_required": false, "updates": {}}
...ignoring
ok: [172.19.8.4]
ok: [172.19.8.6]
fatal: [172.20.8.53]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.20.8.55]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.35]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
fatal: [172.20.8.57]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.20.8.57', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d60e5310>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.52]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.62]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.56]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.63]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 753
fatal: [172.20.8.42]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Searching for updates: Exception from HRESULT: 0x8024402F - External cab file processing completed with some errors (WU_E_PT_ECP_SUCCEEDED_WITH_ERRORS 8024402F)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.64]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 753
fatal: [172.20.8.50]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Searching for updates: Exception from HRESULT: 0x8024402F - External cab file processing completed with some errors (WU_E_PT_ECP_SUCCEEDED_WITH_ERRORS 8024402F)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 753
fatal: [172.20.8.68]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Searching for updates: Exception from HRESULT: 0x80072F8F - Unknown WUA HRESULT 2147954575 (UNKNOWN 80072F8F)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.66]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
fatal: [172.20.8.65]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.20.8.65', port=5985): Read timed out. (read timeout=30)", "unreachable": true}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.67]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 753
fatal: [172.20.8.76]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Searching for updates: Exception from HRESULT: 0x80072F8F - Unknown WUA HRESULT 2147954575 (UNKNOWN 80072F8F)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 753
fatal: [172.20.8.77]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Searching for updates: Exception from HRESULT: 0x80072F8F - Unknown WUA HRESULT 2147954575 (UNKNOWN 80072F8F)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.69]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.73]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.70]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
fatal: [172.20.8.85]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.20.8.88]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.81]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 753
fatal: [172.20.8.82]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Searching for updates: Exception from HRESULT: 0x80072F8F - Unknown WUA HRESULT 2147954575 (UNKNOWN 80072F8F)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 753
fatal: [172.20.8.89]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Searching for updates: Exception from HRESULT: 0x80240438 - There is no route or network connectivity to the endpoint (WU_E_PT_ENDPOINT_UNREACHABLE 80240438)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.78]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
fatal: [172.20.4.13]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.84]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
ok: [172.20.4.14]
fatal: [172.20.4.23]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.91]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 757
fatal: [172.20.8.90]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to search for updates (SuceededWithErrors 3)", "reboot_required": false, "updates": {}}
...ignoring
fatal: [172.20.4.26]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.20.4.28]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.20.4.32]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.20.4.30]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.20.4.34]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
ok: [172.20.4.10]
fatal: [172.20.4.37]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.20.4.38]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.20.4.42]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.20.4.42', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d60c6af0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
ok: [172.20.4.24]
fatal: [172.20.4.45]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
ok: [172.20.4.19]
ok: [172.20.4.44]
ok: [172.20.4.46]
fatal: [172.20.4.55]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.20.5.220]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.20.5.220', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d606cd30>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.20.5.222]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.20.5.222', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6084610>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.17.7.1]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.1', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6194610>: Failed to establish a new connection: [Errno 111] Connection refused'))", "unreachable": true}
fatal: [172.17.7.10]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
ok: [172.20.5.221]
fatal: [172.17.7.23]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 841
fatal: [172.20.4.33]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {"05f6adb4-c6dc-49f5-8e44-3b163ced42dc": {"categories": ["Feature Packs", "Windows 10, version 1903 and later"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "05f6adb4-c6dc-49f5-8e44-3b163ced42dc", "installed": false, "kb": ["5011048"], "title": "Microsoft .NET Framework 4.8.1 for Windows 10 Version 22H2 for x64 (KB5011048)"}, "1a8debc1-842e-4ed2-be89-953d65f96173": {"categories": ["Updates", "Windows 10, version 1903 and later"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "1a8debc1-842e-4ed2-be89-953d65f96173", "installed": false, "kb": ["5029847"], "title": "2023-08 Cumulative Update Preview for .NET Framework 3.5, 4.8 and 4.8.1 for Windows 10 Version 22H2 for x64 (KB5029847)"}}, "found_update_count": 2, "installed_update_count": 0, "msg": "A reboot is required before more updates can be installed", "reboot_required": true, "updates": {"4d52e550-3cd5-4911-b0bd-2812b91580a5": {"categories": ["Definition Updates", "Microsoft Defender Antivirus"], "downloaded": false, "id": "4d52e550-3cd5-4911-b0bd-2812b91580a5", "installed": false, "kb": ["2267602"], "title": "Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.395.1065.0)"}, "d9b8cfaf-4904-4031-a2a5-81d80e25dac5": {"categories": ["Security Updates"], "downloaded": false, "id": "d9b8cfaf-4904-4031-a2a5-81d80e25dac5", "installed": false, "kb": ["5028166"], "title": "2023-07 Cumulative Update for Windows 10 Version 22H2 for x64-based Systems (KB5028166)"}}}
...ignoring
fatal: [172.17.7.25]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.25', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d608a490>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.17.7.30]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.17.7.38]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.38', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d60172b0>: Failed to establish a new connection: [Errno 111] Connection refused'))", "unreachable": true}
ok: [172.20.4.35]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 841
fatal: [172.20.4.51]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {"05f6adb4-c6dc-49f5-8e44-3b163ced42dc": {"categories": ["Feature Packs", "Windows 10, version 1903 and later"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "05f6adb4-c6dc-49f5-8e44-3b163ced42dc", "installed": false, "kb": ["5011048"], "title": "Microsoft .NET Framework 4.8.1 for Windows 10 Version 22H2 for x64 (KB5011048)"}, "1a8debc1-842e-4ed2-be89-953d65f96173": {"categories": ["Updates", "Windows 10, version 1903 and later"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "1a8debc1-842e-4ed2-be89-953d65f96173", "installed": false, "kb": ["5029847"], "title": "2023-08 Cumulative Update Preview for .NET Framework 3.5, 4.8 and 4.8.1 for Windows 10 Version 22H2 for x64 (KB5029847)"}}, "found_update_count": 2, "installed_update_count": 0, "msg": "A reboot is required before more updates can be installed", "reboot_required": true, "updates": {"4d52e550-3cd5-4911-b0bd-2812b91580a5": {"categories": ["Definition Updates", "Microsoft Defender Antivirus"], "downloaded": false, "id": "4d52e550-3cd5-4911-b0bd-2812b91580a5", "installed": false, "kb": ["2267602"], "title": "Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.395.1065.0)"}, "d9b8cfaf-4904-4031-a2a5-81d80e25dac5": {"categories": ["Security Updates"], "downloaded": false, "id": "d9b8cfaf-4904-4031-a2a5-81d80e25dac5", "installed": false, "kb": ["5028166"], "title": "2023-07 Cumulative Update for Windows 10 Version 22H2 for x64-based Systems (KB5028166)"}}}
...ignoring
fatal: [172.17.7.44]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.44', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d600ddf0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.17.7.45]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.45', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d60320a0>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
ok: [172.17.7.39]
fatal: [172.17.7.49]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.49', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d602a910>: Failed to establish a new connection: [Errno 111] Connection refused'))", "unreachable": true}
ok: [172.17.7.29]
fatal: [172.17.7.55]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.55', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6042130>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.17.7.57]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.17.7.58]: UNREACHABLE! => {"changed": false, "msg": "ntlm: Access is denied.  (extended fault data: {'transport_message': 'Bad HTTP response returned from server. Code 500', 'http_status_code': 500, 'wsmanfault_code': '5', 'fault_code': 's:Sender', 'fault_subcode': 'w:AccessDenied'})", "unreachable": true}
fatal: [172.17.7.59]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.59', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6031a30>: Failed to establish a new connection: [Errno 111] Connection refused'))", "unreachable": true}
fatal: [172.17.7.61]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.61', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d6033e50>: Failed to establish a new connection: [Errno 111] Connection refused'))", "unreachable": true}
fatal: [172.17.7.63]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.63', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d5fcf100>: Failed to establish a new connection: [Errno 111] Connection refused'))", "unreachable": true}
fatal: [172.17.7.64]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.64', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d604b3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))", "unreachable": true}
fatal: [172.17.7.66]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.17.7.67]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.67', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d603cd30>: Failed to establish a new connection: [Errno 111] Connection refused'))", "unreachable": true}
fatal: [172.17.7.70]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.70', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d603dcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))", "unreachable": true}
fatal: [172.17.7.73]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.17.7.74]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.74', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d5fd4790>: Failed to establish a new connection: [Errno 113] No route to host'))", "unreachable": true}
fatal: [172.17.7.77]: UNREACHABLE! => {"changed": false, "msg": "ntlm: Access is denied.  (extended fault data: {'transport_message': 'Bad HTTP response returned from server. Code 500', 'http_status_code': 500, 'wsmanfault_code': '5', 'fault_code': 's:Sender', 'fault_subcode': 'w:AccessDenied'})", "unreachable": true}
fatal: [172.17.7.79]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.17.7.81]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
ok: [172.17.7.51]
fatal: [172.17.7.87]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.17.7.89]: UNREACHABLE! => {"changed": false, "msg": "ntlm: Access is denied.  (extended fault data: {'transport_message': 'Bad HTTP response returned from server. Code 500', 'http_status_code': 500, 'wsmanfault_code': '5', 'fault_code': 's:Sender', 'fault_subcode': 'w:AccessDenied'})", "unreachable": true}
fatal: [172.17.7.91]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.91', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f28d5fed550>: Failed to establish a new connection: [Errno 111] Connection refused'))", "unreachable": true}
fatal: [172.17.7.97]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.17.7.98]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.17.7.114]: UNREACHABLE! => {"changed": false, "msg": "ntlm: the specified credentials were rejected by the server", "unreachable": true}
fatal: [172.17.7.41]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPConnectionPool(host='172.17.7.41', port=5985): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f28d60169a0>, 'Connection to 172.17.7.41 timed out. (connect timeout=30)'))", "unreachable": true}
changed: [172.17.7.47]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 841
fatal: [172.17.7.82]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {"05f6adb4-c6dc-49f5-8e44-3b163ced42dc": {"categories": ["Feature Packs", "Windows 10, version 1903 and later"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "05f6adb4-c6dc-49f5-8e44-3b163ced42dc", "installed": false, "kb": ["5011048"], "title": "Microsoft .NET Framework 4.8.1 for Windows 10 Version 22H2 for x64 (KB5011048)"}, "0614003b-dfa9-4c2e-bfab-64451af63b67": {"categories": ["Drivers"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "0614003b-dfa9-4c2e-bfab-64451af63b67", "installed": false, "kb": [], "title": "Intel - Other hardware - Intel(R) 200 Series Chipset Family Thermal subsystem - A2B1"}, "078bf4fe-5286-4d8b-b6c0-7f9d27b10c03": {"categories": ["Drivers"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "078bf4fe-5286-4d8b-b6c0-7f9d27b10c03", "installed": false, "kb": [], "title": "HP Inc. - Firmware - 2.47.0.0"}, "1a8debc1-842e-4ed2-be89-953d65f96173": {"categories": ["Updates", "Windows 10, version 1903 and later"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "1a8debc1-842e-4ed2-be89-953d65f96173", "installed": false, "kb": ["5029847"], "title": "2023-08 Cumulative Update Preview for .NET Framework 3.5, 4.8 and 4.8.1 for Windows 10 Version 22H2 for x64 (KB5029847)"}, "2053e61e-5d0a-4058-9f7d-29a704d3a77b": {"categories": ["Drivers"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "2053e61e-5d0a-4058-9f7d-29a704d3a77b", "installed": false, "kb": [], "title": "Intel Corporation - SoftwareComponent - 2.19.100.4"}, "31e5e2aa-8c00-494f-bdfa-42996f20e234": {"categories": ["Drivers"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "31e5e2aa-8c00-494f-bdfa-42996f20e234", "installed": false, "kb": [], "title": "Intel - Other hardware - Intel(R) 200 Series Chipset Family LPC Controller (Q270) - A2C6"}, "49866094-d011-49bf-a15e-7fd88fc30682": {"categories": ["Drivers"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "49866094-d011-49bf-a15e-7fd88fc30682", "installed": false, "kb": [], "title": "Intel Corporation - System - 2.19.100.4"}, "4c0ebaaa-6c94-445a-9c12-62420b36dba1": {"categories": ["Drivers"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "4c0ebaaa-6c94-445a-9c12-62420b36dba1", "installed": false, "kb": [], "title": "Intel - Other hardware - Intel(R) 200 Series Chipset Family PMC - A2A1"}, "696b0b73-1f4e-445d-b93c-81fcc92c80cf": {"categories": ["Drivers"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "696b0b73-1f4e-445d-b93c-81fcc92c80cf", "installed": false, "kb": [], "title": "Intel - Other hardware - Intel(R) 200 Series Chipset Family PCI Express Root Port #9 - A298"}, "7a656106-e24e-4fea-bc5a-f7f803a5b47d": {"categories": ["Drivers"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "7a656106-e24e-4fea-bc5a-f7f803a5b47d", "installed": false, "kb": [], "title": "Intel - Other hardware - Intel(R) Xeon(R) E3 - 1200/1500 v5/6th Gen Intel(R) Core(TM) Host Bridge/DRAM Registers - 191F"}, "9288099d-3d44-48f8-bd17-18c923de9797": {"categories": ["Drivers"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "9288099d-3d44-48f8-bd17-18c923de9797", "installed": false, "kb": [], "title": "Intel - Other hardware - Intel(R) 200 Series Chipset Family SMBUS - A2A3"}, "fdc976a5-3223-476e-aa03-fe57be06e90a": {"categories": ["Drivers"], "downloaded": false, "filtered_reason": "category_names", "filtered_reasons": ["category_names"], "id": "fdc976a5-3223-476e-aa03-fe57be06e90a", "installed": false, "kb": [], "title": "Intel - System - 2306.4.3.0"}}, "found_update_count": 1, "installed_update_count": 0, "msg": "A reboot is required before more updates can be installed", "reboot_required": true, "updates": {"d9b8cfaf-4904-4031-a2a5-81d80e25dac5": {"categories": ["Security Updates"], "downloaded": false, "id": "d9b8cfaf-4904-4031-a2a5-81d80e25dac5", "installed": false, "kb": ["5028166"], "title": "2023-07 Cumulative Update for Windows 10 Version 22H2 for x64-based Systems (KB5028166)"}}}
...ignoring
changed: [172.17.7.11]

TASK [reboot host if required] *************************************************
skipping: [172.19.8.4]
skipping: [172.19.8.6]
skipping: [172.20.8.16]
skipping: [172.20.8.35]
skipping: [172.20.8.42]
skipping: [172.20.8.50]
skipping: [172.20.8.52]
skipping: [172.20.8.56]
skipping: [172.20.8.62]
skipping: [172.20.8.63]
skipping: [172.20.8.64]
skipping: [172.20.8.66]
skipping: [172.20.8.67]
skipping: [172.20.8.68]
skipping: [172.20.8.70]
skipping: [172.20.8.69]
skipping: [172.20.8.73]
skipping: [172.20.8.76]
skipping: [172.20.8.77]
skipping: [172.20.8.78]
skipping: [172.20.8.81]
skipping: [172.20.8.82]
skipping: [172.20.8.84]
skipping: [172.20.8.89]
skipping: [172.20.8.90]
skipping: [172.20.8.91]
skipping: [172.20.4.24]
skipping: [172.20.4.10]
skipping: [172.20.4.14]
skipping: [172.20.4.19]
skipping: [172.20.4.35]
skipping: [172.20.4.46]
skipping: [172.20.4.44]
skipping: [172.17.7.29]
skipping: [172.17.7.39]
skipping: [172.17.7.47]
skipping: [172.17.7.51]
